name: Unit Tests

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # 保持与你 Docker 镜像一致

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 按照你的需求填充依赖 [cite: 2026-01-09]
        pip install -r requirements.txt
        # 安装测试专用工具 [cite: 2026-01-09]
        pip install pytest pytest-cov coverage flake8 protobuf datasets

    - name: Run Pytest with Coverage
      run: |
        pytest --cov=src tests/